apiVersion: apps/v1
kind: Deployment
metadata:
  name: workloads
  labels:
    app: workloads
spec:
  selector:
    matchLabels:
      app: workloads
  template:
    metadata:
      labels:
        app: workloads
    spec:
      containers:
      - name: workloads
        image: 'image-registry.openshift-image-registry.svc:5000/pmi/workloads:latest'
        ports:
        - containerPort: 9443
        - containerPort: 9080
--- 
apiVersion: v1
kind: Service
metadata:
  name: workloads
  labels:
    app: workloads
spec:
  selector:
    app: workloads
  ports:
  - name: http
    port: 9080
  - name: https
    port: 9443
---
apiVersion: v1
kind: Route
metadata:
  name: workloads
  labels:
    app: workloads
spec:
  to:
    kind: Service
    name: workloads
  port:
    targetPort: http
